export enum ListStudentLessonReportsResultKind {
  LISTED = "LISTED",
  TEACHER_NOT_FOUND = "TEACHER_NOT_FOUND",
  USER_IS_NOT_TEACHER = "USER_IS_NOT_TEACHER",
  STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND",
}