import { Student } from "@/modules/students/domain/student";

export const mockStudents: Student[] = [
  {
    id: "student_1",
    teacherUserId: "teacher_1",
    fullName: "Анна Смирнова",
    subject: "Математика",
    level: "7 класс",
    goals: "Подтянуть алгебру и подготовиться к контрольным работам.",
    notes: "Сильна в геометрии, но путается в уравнениях.",
    createdAt: "2026-04-02T09:00:00.000Z",
    updatedAt: "2026-04-02T09:00:00.000Z",
  },
  {
    id: "student_2",
    teacherUserId: "teacher_1",
    fullName: "Илья Кузнецов",
    subject: "Английский язык",
    level: "A2",
    goals: "Разговорный английский для поездок и школы.",
    notes: "Хорошо воспринимает на слух, но стесняется говорить.",
    createdAt: "2026-04-02T09:10:00.000Z",
    updatedAt: "2026-04-02T09:10:00.000Z",
  },
  {
    id: "student_3",
    teacherUserId: "teacher_1",
    fullName: "Мария Волкова",
    subject: "Русский язык",
    level: "9 класс",
    goals: "Подготовка к ОГЭ, работа над сочинением и пунктуацией.",
    notes: "Нужна системность и регулярное повторение правил.",
    createdAt: "2026-04-02T09:20:00.000Z",
    updatedAt: "2026-04-02T09:20:00.000Z",
  },
  {
    id: "student_4",
    teacherUserId: "teacher_1",
    fullName: "Даниил Орлов",
    subject: "Физика",
    level: "10 класс",
    goals: "Лучше понимать задачи по механике и подготовиться к экзамену.",
    notes: "Теорию знает средне, задачи решает медленно.",
    createdAt: "2026-04-02T09:30:00.000Z",
    updatedAt: "2026-04-02T09:30:00.000Z",
  },
  {
    id: "student_5",
    teacherUserId: "teacher_1",
    fullName: "София Павлова",
    subject: "Химия",
    level: null,
    goals: "Освоить базовые темы и устранить пробелы по школьной программе.",
    notes: null,
    createdAt: "2026-04-02T09:40:00.000Z",
    updatedAt: "2026-04-02T09:40:00.000Z",
  },
];
